services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    ports:
      - "${BACKEND_EXPOSED_PORT:-5000}:5000"

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./.env
    ports:
      - "${FRONTEND_EXPOSED_PORT:-3000}:3000"
    depends_on:
      - backend

